### ISSUE TITLE
Add missing slides

### ISSUE THREAD

**Issue by bebraw** [GraphQLFinland/slides#2]
**TODO:**

* [ ] 1 - Adam Miskiewicz - **Asked (Juho)**

**Comment by bebraw** [comment]
CC @skevy. When you have time, could you please send us GraphQL Finland 2018 slides in pdf format? Thanks. 👍

**Comment by skevy** [comment]
@bebraw here you go! http://s.sk3vy.com/ba2e532f228f

**Comment by bebraw** [comment]
@skevy Perfect. Thanks a lot!
